### ISSUE TITLE
Testar JWT- Passar informações do Usuário do Portal para outra aplicação

### ISSUE THREAD

**Issue by emmanuelneri** [emmanuelneri/arquitetura-microservices#3]
A projeto Portal terá uma lista de aplicações dentro de sua configuração, de acordo com essa lista será gerado o menu de aplicações que o usuário tem acesso através do Portal.

Ao clicar em uma aplicação no Portal será gerado um token através do JWT contendo informações do usuário necessária para que a aplicação de destino possa ser autenticada. O token gerado será concatenado com a url cadastrada na configuração de aplicação, ex: http://localhost:8080/vendas/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbFVzdWFyaW8iOiJ0ZXN0ZUBnbWFpbC5jb20ifQ.VuinLSfLoHnfXWxDEyukuiAp8NighvjQ-5z1A5fR-ng

O Modulo de destino receberá o token via parâmetro e fará a leitura do token com JWT, para ter acesso as informações vindas do Portal , com isso será possível autenticar no módulo e carregar as permissões necessárias.

**Comment by emmanuelneri** [comment]
Primeiro token gerado via aplicação: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbFVzdWFyaW8iOiJ0ZXN0ZUBnbWFpbC5jb20ifQ.VuinLSfLoHnfXWxDEyukuiAp8NighvjQ-5z1A5fR-ng

Obs: Para testar apenas colar token no Debuger no site http://jwt.io/

**Comment by filipenevola** [comment]
Isso mesmo :) Estamos no caminho.

**Comment by emmanuelneri** [comment]
Solução desenvolvida

Portal:

Configuração:
- Cria Aplicação(Modulo);
- Configurar URL da aplicação;

Ao clicar no menu o sistema gera um token baseado no usuário e redireciona para aplicação.

Vendas:
- Filtro escuta a url /vendas/auth esperando o parâmetro de request token;
- Caso encontrado o parâmetro é decodificado o token, via JWT, dessa forma é criado o UsuarioToken customizado do shiro, o qual posteriormente será transformado em Usuário e adicionado na sessão valida, gerenciada pelo shiro
